# version: '3.8'

services:
  postgres_server:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_PASSWORD: agrotech
      POSTGRES_USER: agro
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - public_network

networks:
  public_network:
    driver: bridge
  default:
    name: public_network
    external: true

volumes:
  postgres_data:
